export default [
    {
        title: "CASINO SPACE WEB",
        brief: "",
        cover: require("../assets/images/working/works_web8.jpg"),
        id: 1,
    },
    {
        title: "CASINO OCEAN",
        brief: "",
        cover: require("../assets/images/working/works_web9.jpg"),
        id: 2,
    },
    {
        title: "CASINO METEORITE",
        brief: "",
        cover: require("../assets/images/working/works_web10.jpg"),
        id: 3,
    },
    {
        title: "CASINO ORANGE-WHITE",
        brief: "",
        cover: require("../assets/images/working/works_web11.jpg"),
        id: 4,
    },
    {
        title: "CASINO GAME",
        brief: "",
        cover: require("../assets/images/working/works_web12.jpg"),
        id: 5,
    },
    {
        title: "DISPLAY PAGE",
        brief: "",
        cover: require("../assets/images/working/works_web13.jpg"),
        id: 6,
    },
    // {
    //     title: "G CASINO",
    //     brief: "運用新的排版方式製作與以往不同的遊戲網頁，將選項欄放在下方，好讓用戶能了解自己目前在什麼區， 將重點都擺放至中間，讓玩家能更專注於網頁。",
    //     cover: require("../assets/images/working/works_web1.jpg"),
    //     showText: "*點擊圖片連結作品",
    //     link: "http://art-demo.sog88.net/personal_demo/donny/20181018_%E7%8F%BE%E9%87%91%E7%B6%B2%E5%85%AC%E7%89%88_%E5%88%87%E7%89%88/",
    //     id: 8,
    // },
    {
        title: "POKER GAME",
        brief: "運用亮麗色彩製作讓畫面更活潑，中間區塊也能讓玩家自由條動，更換自己擺設喜愛的項目。",
        cover: require("../assets/images/working/works_web2.jpg"),
        id: 7,
    },
    {
        title: "i88GAME",
        brief: "參考國外製作時尚雜誌網頁來去設計，顏色利用簡單白紅來做基底，而左邊欄能輕易選擇想玩的遊戲，中間則展示重要商品資訊。",
        cover: require("../assets/images/working/works_web3.jpg"),
        id: 8,
    },
    // {
    //     title: "CASINO",
    //     brief: "參考歐美遊戲網頁來製作，顏色上選擇較活潑色，按鈕製作漂浮感，使畫面整體看起來更生動。",
    //     cover: require("../assets/images/working/works_web4.jpg"),
    //     showText: "*點擊圖片連結作品",
    //     link: "http://art-demo.sog88.net/personal_demo/donny/20180820_%E7%8F%BE%E9%87%91%E7%B6%B2%E5%88%87%E7%89%88%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%85%20OK/",
    //     id: 14,
    // },
    // {
    //     title: "Facebook",
    //     brief: "重新設計Facebook，將icon改為較活潑感，系統都放置左邊， 而右半部想讓用戶能過濾掉很多廣告，也把自己喜愛的相關貼文分區，選擇幾喜愛的排版，跟戶能者更多的互動。",
    //     cover: require("../assets/images/working/works_web5.png"),
    //     id: 12,
    // },
    {
        title: "競賽GAME",
        brief: "左邊欄位能自己調整想先觀賞的項目順序，而中間項目匡也會跟整更換，讓用戶能更自由選擇自己想要的項目。",
        cover: require("../assets/images/working/works_web6.jpg"),
        id: 9,
    },
    {
        title: "Atrust-金融網站",
        brief: "FinTech網頁，首頁特效設計像駭客任務一堆數字，像金融網頁對數字的敏銳度，也讓客人一進到這網頁更有感覺。",
        cover: require("../assets/images/working/works_web7.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://www.atrustek.com/cis/#/home",
        id: 10,
    },
    {
        title: "36588GAME",
        brief: "產品需要製作體育遊戲APP，在製作時版面背景利用了體育場來當背景， 而切換icon利用真實球種，來增加玩家對產品的視覺感。",
        cover: require("../assets/images/working/works_app1.jpg"),
        id: 11,
    },
    {
        title: "i88GAME",
        brief: "製作遊戲網站APP，因商品客戶群年紀偏大，所以製作時將按鈕做得較大，讓客戶好操作，也運用圖片來襯托每一個款遊戲的豐富感。",
        cover: require("../assets/images/working/works_app2.jpg"),
        id: 12,
    },
    // {
    //     title: "UI100 計算機",
    //     brief: "在操作上制作可往右滑直接選擇需要的符號，不需再一直把手機擺橫的，可直接選擇輕鬆又快速。",
    //     cover: require("../assets/images/working/works_app3.jpg"),
    //     id: 3,
    // },
    {
        title: "UI100 用戶資料",
        brief: "在畫面上讓用戶者能容易了解自己目前的追蹤人數，也能輕易的選擇想觀看的照片，和快速瀏攬留言與回覆。",
        cover: require("../assets/images/working/works_app4.jpg"),
        id: 13,
    },
    {
        title: "UI100 項目管理",
        brief: "運用簡單的色彩，讓用戶者能一事情重要性來分配顏色，也能讓畫面感更豐富，操作也製作的淺顯易懂。",
        cover: require("../assets/images/working/works_app5.png"),
        id: 14,
    },
    {
        title: "UI100 信用卡",
        brief: "讓客戶能挑選自己適用的信用卡，商品價格要分明，操作上簡單，喜歡就直接按打勾購買。",
        cover: require("../assets/images/working/works_app6.jpg"),
        id: 15,
    },
    // {
    //     title: "UI100 鬧鐘",
    //     brief: "設計黑白簡單風格，背景會隨著時間也跟著改變",
    //     cover: require("../assets/images/working/works_app7.png"),
    //     id: 7,
    // },

    {
        title: "PK08",
        brief: "設計飄浮球場，於背景活潑漸層色搭配，讓整體畫面更生動。",
        cover: require("../assets/images/working/works_other1.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/pk08/",
        id: 16,
    },
    // {
    //     title: "S77",
    //     brief: "運用3D圖片的美感，來製作出不同的遊戲登入頁。",
    //     cover: require("../assets/images/working/works_other2.jpg"),
    //     showText: "*點擊圖片連結作品",
    //     link: "http://donny821223.000webhostapp.com/works/s77/",
    //     id: 18,
    // },
    {
        title: "DS17",
        brief: "運用燈光與背景效果，設計畫面出較像高質感的遊戲登入頁面。",
        cover: require("../assets/images/working/works_other3.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/ds17/",
        id: 17,
    },
    // {
    //     title: "30678",
    //     brief: "運用斜線條來製作有速度衝擊感的登入頁面。",
    //     cover: require("../assets/images/working/works_other4.jpg"),
    //     showText: "*點擊圖片連結作品",
    //     link: "http://donny821223.000webhostapp.com/works/30678/",
    //     id: 22,
    // },
    {
        title: "AHA8",
        brief: "設計衝擊與爆破的視覺感，讓畫面感更強烈。",
        cover: require("../assets/images/working/works_other5.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/aha8/",
        id: 18,
    },
    {
        title: "故障燈",
        brief: "畫面設計開關燈效果，讓用戶看到就算無法登入網頁時，也能用俏皮的方式來顯現網頁故障。",
        cover: require("../assets/images/working/works_4041.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/404_light/",
        id: 19,
    },
    {
        title: "船兒漂泊",
        brief: "網頁中的小船移動搭配鴿子無理的對話，讓就算再故障網頁能很有趣。",
        cover: require("../assets/images/working/works_4042.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/404_ferry/",
        id: 20,
    },
    {
        title: "齒輪轉動",
        brief: "設計齒輪轉動感覺讓用戶覺得網站是很認真的在維護。",
        cover: require("../assets/images/working/works_4043.jpg"),
        showText: "*點擊圖片連結作品",
        link: "http://donny821223.000webhostapp.com/works/404_gear/",
        id: 21,
    },
    {
        title: "體育廣告",
        brief: "",
        cover: require("../assets/images/working/works_banner1.jpg"),
        id: 22,
    },
    {
        title: "WM娛樂廣告",
        brief: "",
        cover: require("../assets/images/working/works_banner2.jpg"),
        id: 23,
    },
    {
        title: "牛年廣告",
        brief: "",
        cover: require("../assets/images/working/works_banner3.jpg"),
        id: 24,
    },
    {
        title: "JP娛樂廣告",
        brief: "",
        cover: require("../assets/images/working/works_banner4.jpg"),
        id: 25,
    },

];